### ISSUE TITLE
test: "fuzzing" OpenThread to provide robustness and negative stress testing

### ISSUE THREAD

**Issue by turon** [openthread/openthread#129]
We have good positive path test coverage of OpenThread now using `make check` and the CI test suite.

Perhaps the negative path test coverage of OpenThread could be built using "fuzzing" techniques, and some of the tools available in that space.

The GDS [blog](http://blog.gdssecurity.com/labs/2015/9/21/fuzzing-the-mbed-tls-library.html) discusses the technique, good open source tools to implement it, and even have examples applying the method to an instrumented mbedtls:

> "Fuzzing is a testing technique that feeds a program under inspection with random inputs and observes its behavior. The goal of fuzzing is to discover bugs in the inspected program."

**Comment by darconeous** [comment]
We should also fuzz spinel.

**Comment by darconeous** [comment]
OpenThread really needs a comprehensive fuzz/fault-insertion testing plan, and this seems like the most appropriate issue to track that with.

I'm bumping this up in priority to increase visibility. Also adding the "**help wanted**" tag, since @mturon doesn't necessarily have to be the person to implement it.

Tagging @jwhui, @abtink, and @nibanks for comment.

**Comment by jwhui** [comment]
I'm starting work on adding initial fuzz testing support.
