### ISSUE TITLE
Commissioning is broke in Conformance Tests from GRL

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/openthread#2350]
We think this Issue: https://github.com/openthread/openthread/issues/2254
And this merge: https://github.com/openthread/openthread/pull/2311

Is causing some problems with the Thread Conformance/Certification scripts from GRL

Which assumes the previous functionality...

In the end, the commissioning tests fail.

**Comment by DuaneEllis-TI** [comment]
Hmm - Update on this - 

The GRL  DUT code for the commissioner tests is given/passed as a parameter the EUI64 - then for the openthread configuration it calculates a the HASH MAC and performs the ADD  using the HASHMAC

The solution is quite simple:  require 2 different Python scripts for openthread based devices.

Version: Original - remains unchanged

Version: NEW - passes the EUI64 not the HASHMAC ... to the DUT.

**Comment by jwhui** [comment]
@DuaneEllis-TI, I'm not quite clear on what the issue is, but let me try to answer:

OpenThread reference devices driven by the Thread Test Harness should use the OpenThread python script provided with the Thread Test Harness.

For the OpenThread DUT device:
1) Drive the DUT manually.
2) Add the latest OpenThread.py file from GitHub as a [new reference platform](https://openthread.io/certification/automation_setup#acting_as_a_new_reference_platform).

I believe your "2 different Python scripts" is the latter option above.

Is there anything that we need to change on GitHub to address your issue?

**Comment by jwhui** [comment]
@DuaneEllis-TI, were you able to make progress on this issue?

**Comment by DuaneEllis-TI** [comment]
Yes we have - sorry should have updated this issue and closed it earlier.
