### ISSUE TITLE
How to download Thread-Test-Harness1.1-Alpha v1.0-Release_40.0

### ISSUE THREAD

**Issue by philixwan** [openthread/openthread#2470]
Hello, We want to use the automatic test for openthread. Can you help me where we can download Thread-Test-Harness1.1-Alpha v1.0-Release_40.0?

**Comment by jwhui** [comment]
Follow the instructions here: http://graniteriverlabs.com/thread/

**Comment by philixwan** [comment]
But I can download just the latest version from here, Is this version used as Harness Automation Tool?

**Comment by jwhui** [comment]
You should use the latest version available at the link above.

**Comment by librasungirl** [comment]
There are many updates in TH since Alpha v1.0-Release_40.0. It may not have much sense to run with this out-of-date version.
We have realized that the automation tool may not work well with the latest TH R1.2.0 and I believe @FiveDimensions is working on this. Please help to update when there is any progress @FiveDimensions, thanks!
Before the automation tool is ready, TH itself provides another AUTO_DUT way to accelerate the regression. Please refer to Test Harness Auto DUT mode (https://openthread.io/certification/automation_setup) or TH Quick-Start-Guide for details.
Hope it helps.

**Comment by philixwan** [comment]
Thank you very much.
