### ISSUE TITLE
bootstrap and make file failed

### ISSUE THREAD

**Issue by joker9357** [openthread/openthread#2730]
I'm new for raspberry pi and I am setting up the development environment on raspbian following the tutorial.
when I executed the "./script/bootstrap" it told me 

"Unable to locate package 'clang-format-5.0' "

and then I checked the bootstrap file and apt list, there is no clang-format-5.0 in apt list.

So I replaced the 5.0 with 4.0.

As a result, when I make file, there are a lot of nothing to be done error. and the test failed.

Can some one help?

**Comment by jwhui** [comment]
clang-format 5.0 is required for automated code formatting using the `make pretty` target.  If you do not care about automated formatting, you can just comment that line out.

Rather than relying on apt-get, you could try to directly use the [official build for Clang 5](http://releases.llvm.org/5.0.0/clang%2bllvm-5.0.0-armv7a-linux-gnueabihf.tar.xz).  Then comment out the clang-format-5.0 install line in `script/bootstrap`.
