### ISSUE TITLE
otLinkOutOfBandTransmitRequest() and otPlatRadioTransmit()

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#2867]
According to #2488, `otLinkOutOfBandTransmitRequest()` is designed to be in conjunction with other mac operation which includes normal transmission. However, `otPlatRadioTransmit()` is designed to accept buffer provided by `otPlatRadioGetTransmitBuffer()` only(see https://github.com/openthread/openthread/blob/master/include/openthread/platform/radio.h#L422), which returns a single static buffer on most example platforms. If  `otLinkOutOfBandTransmitRequest()` respect the definition of `otPlatRadioTransmit()` and get the buffer from `otPlatRadioGetTransmitBuffer()`, it could destroy data of normal transmission, and If `otLinkOutOfBandTransmitRequest()` ignores the design and constructs its own buffer, it may not be properly processed(at least on platform posix and nrf82540).

Shall we adjust the design of `otPlatRadioTransmit()` or shall we forbid initiating requests to send normal Thread frame and out of bound frame simultaneously?

**Comment by pvanhorn** [comment]
Hi Yakun.  It is expected that a module which calls otLinkOutOfBandTransmitRequest would have also called otPlatRadioGetTransmitBuffer to acquire a valid buffer.  Therefore systems that expect to call otLinkOutOfBandTransmitRequest, must implement otPlatRadioGetTransmitBuffer, such that it can provide multiple buffers.  Since the call to otLinkOutOfBandTransmitRequest and the implementation of otPlatRadioGetTransmitBuffer are both implemented by the 3rd party, this should not pose a problem.  Finally, we use this feature internally at Nest.
