### ISSUE TITLE
[travis] posix-app-ncp test fails frequently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#3635]
@bukepo, any thoughts?

**Comment by bukepo** [comment]
Yes, this requires a more complicated implementation to ensure the synchronization of all components(`ot-ncp-radio`, `ot-ncp-?td`, `pyspinel-cli.py` and `node_cli.py`). I will look into this ASAP.

**Comment by jwhui** [comment]
It appears Cert_7_1_03 is the one that fails most frequently and fails because the SED does not autoconfigure IPv6 addresses with the on-mesh prefix.

**Comment by bukepo** [comment]
Maybe should temporarily disable the test case. I don't have time to fix it for now.

**Comment by jwhui** [comment]
Just submitted #3683 to temporarily remove posix-app-ncp test.

**Comment by LuDuda** [comment]
@bukepo from your first answer I see that you are aware of the root cause of this problem. Can you elaborate more on that? Is that issue only related to virtual time, or fundamentally RCP architecture is not stable?

**Comment by bukepo** [comment]
Yes, the root cause was that when Travis is busy, the process scheduler may not schedule running order of processes of ot-ncp-radio, ot-ncp, pyspinel-cli and virtual time simulator as we expect. I added more virtual events to guarantee the order. However, I happened to think the order is not guaranteed in real situations, so I didn't submit the complicated version. I will look into this issue when I have time.
