### ISSUE TITLE
[mle] certification tests ED_6_1_6, SED_6_1_6, Router_5_1_11 fail

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#3847]
I have verified that because of #3803, ED_6_1_6, SED_6_1_6 and Router_5_1_11 fail.

The OT built from the previous commit successfully passes the certification test cases.

The device seems to attach to the first Router instead of sending another Parent Request with modified Scan Mask and attach to the REED.

Wireshark reference for ED_6_1_6: [Test_6_1_6.zip](https://github.com/openthread/openthread/files/3201756/Test_6_1_6.zip)

We're investigating the issue, but help would be appreciated 😄

**Comment by jwhui** [comment]
@LuDuda, thanks for identifying this issue!

I believe the issue is that the [check for Link Quality being 3](https://github.com/openthread/openthread/blob/master/src/core/thread/mle.cpp#L1641) is only for the receive direction and does not consider the bi-directional link quality.

I can submit a quick fix soon.

**Comment by LuDuda** [comment]
Yes, it also aligns with my static code analysis.

Thank you for a fix proposal! I can verify it tomorrow.
