### ISSUE TITLE
Monitoring nodes

### ISSUE THREAD

**Issue by jaimemi** [openthread/openthread#3908]
Hi!

I am trying to make a real-time fault tolerant system in which the network will  notice when one of the nodes is down. 

So far, I've tried to use CoAP sending messages back and forth, with watchdogs and so on, but it seems that the network colapses a little bit with so many messages.

I am quite sure there is something Open Thread itself implements to manage this problem, cause for example, when asking for a router table from the CLI, the table refreshes every time there is a new node or a node missing. 

I saw on the Open Thread API that there exists a callback function called void  `(* otNeighborTableCallback)(otNeighborTableEvent aEvent, const otNeighborTableEntryInfo *aEntryInfo)` that provides exactly this feature, but this is from the 2018 release, but I'm afraid I am using a nRF52840 Development Kit from Nordic, and they did not implement it on the last SDK. Is there any other from previous versions with which I could do exactly the same? Could you give me any other idea? My idea was also connecting the Thread Network to the internet, is there any way of runing the last version of Thread in a Raspberry Pi and have that feature?

Thank you very much!

**Comment by jwhui** [comment]
By design, Thread devices do not maintain state about all devices in a Thread network. For routing purposes, routers do maintain state about all other Thread routers in the network. However, for end-devices, routers only maintain state about their directly-attached children.

On a router/leader, take a look at:

- [otThreadGetChildInfoByIndex()](https://openthread.io/reference/group/api-thread-router#otthreadgetchildinfobyindex) for inspecting the child table
- [otThreadGetRouterInfo()](https://openthread.io/reference/group/api-thread-router#otthreadgetrouterinfo) for inspecting the router table

Hope that helps.
