### ISSUE TITLE
[posix-sim] ICMPv6 checksum is incorrect

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4070]
**Describe the bug**
ICMPv6 checksum is incorrect.

**To Reproduce**
Information to reproduce the behavior, including:
1. build: `./bootstrap && ./script/test clean build cert tests/scripts/thread-cert/Cert_5_1_01_RouterAttach.py`
2. Open current.pcap with WireShark

**Expected behavior**
The checksum of ping should be correct.

**Console/log output**
The checksum is wrong.

**Additional context**
None

**Comment by simonlingoogle** [comment]
This issue was caused because openthread posix uses `fdde:ad00:beef::/64` as mesh local prefix, but 6LoWPAN protocol in the Wireshark is not configured with this prefix as Context Id 0. 

Since 6LoWPAN compresses source address and destination address, the correct mesh local prefix `fdde:ad00:beef::/64` is stripped from the packet data and Wireshark had to use it's own configuration to calculate the ICMPv6 checksum, causing checksum mismatch. 

So this is not an openthread issue, but a wireshark configuration mismatch.
