### ISSUE TITLE
In EFR32MG12 (and probably other SL flavors) radio power level state variable out of sync

### ISSUE THREAD

**Issue by theHurc** [openthread/openthread#5510]
https://github.com/openthread/openthread/blob/cf1057b7806f6238404bf5c7340837c7f5a3cc04/examples/platforms/efr32mg12/radio.c#L1134

https://github.com/openthread/openthread/blob/cf1057b7806f6238404bf5c7340837c7f5a3cc04/examples/platforms/efr32mg12/radio.c#L1121

In both the `otPlatRadioSetTransmitPower` and `otPlatRadioGetTransmitPower` implementations a variable `sTxPowerDbm` is used to keep track of the radio power level. But this variable can easily get out of sync because the call `RAIL_SetTxPowerDbm` silently truncates any power level to the nearest power level available for the radio. Why not remove this extra state variable and use `RAIL_GetTxPowerDbm` (divided by 10 of course) to report the actual, set power level for the radio?

**Comment by romacdon** [comment]
@theHurc it looks like `sTxPowerDbm` was introduced in this commit https://github.com/openthread/openthread/commit/eb7a9106388a4e43c5e43028a011fe9abe7befe0 and was used in more than just the `otPlatRadioSetTransmitPower` and `otPlatRadioGetTransmitPower`.  However, since then its use in those other locations has been removed so I agree we should eliminate `sTxPowerDbm` and simply call `RAIL_SetTxPowerDbm` and `RAIL_GetTxPowerDbm`.  We can make that change in an upcoming PR or if you want you can make the change.

**Comment by theHurc** [comment]
I'll leave it to SL. Thanks.
