### ISSUE TITLE
Missing jitters for responses to MLE Parent Request/Link Request

### ISSUE THREAD

**Issue by rlubos** [openthread/openthread#598]
Both Thread Specifications and Certification Test Plan define that responses for MLE Parent Requests must be delayed by a random jitter (up to 500 ms for Router only request, and up to 1000 ms for the second request). I'm not sure if this is currenty covered by test plan, it may be in the final version. The same applies for responses to multicast MLE Link Requests (up to 1000 ms).

Also I have a question regarding Mle::BecomeChild function. Why is the initial MLE Parent Request delayed by 1000 ms? Is this a overlook, or are there any implementation-specific reasons for that?

**Comment by jwhui** [comment]
> Both Thread Specifications and Certification Test Plan define that responses for MLE Parent Requests must be delayed by a random jitter (up to 500 ms for Router only request, and up to 1000 ms for the second request). I'm not sure if this is currenty covered by test plan, it may be in the final version. The same applies for responses to multicast MLE Link Requests (up to 1000 ms).

This has been a TODO, but low priority because the Certification Test Plan does not test for this behavior.  Are you willing to submit a PR to address this issue?

> Also I have a question regarding Mle::BecomeChild function. Why is the initial MLE Parent Request delayed by 1000 ms? Is this a overlook, or are there any implementation-specific reasons for that?

I don't think there's any reason it should be delayed by a fixed value.  While the Thread Spec does not indicate delaying by a random value, there might be reason to do so (e.g. in the case of merging partitions to avoid a large number of nodes responding to an MLE Advertisement at the same time).  Thoughts?

**Comment by rlubos** [comment]
Well, randomizing the initial delay might indeed be beneficial and it seems to me like a good improvement, and as long as it doesn't make tests to fail, it is ok for me.

I will address the missing jitter issue and submit a PR soon.
