### ISSUE TITLE
[github-actions] test_mlr_multicast_routing_across_thread_pans.py fails intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#6290]
**Describe the bug**

tests/scripts/thread-cert/backbone/test_mlr_multicast_routing_across_thread_pans.py fails intermittently.

**Console/log output**

- [logs_61113.zip](https://github.com/openthread/openthread/files/6150846/logs_61113.zip)
- [thread-1-2-backbone-results.zip](https://github.com/openthread/openthread/files/6150847/thread-1-2-backbone-results.zip)

**Comment by simonlingoogle** [comment]
**Seems like our real-time sniffer failed to capture all the Thread traffic during the multicast ping process.** 

The test topology is like: `Host` <---> `PBBR1` <---> `Router1`.

In the test, `Host` pinged a multicast address that `Router1` has subscribed and expect `Router1` to send the ping reply. 

The issue is that there is no `Router1`'s `Ping Reply` in the Thread traffic. 

However, we can actually find `Router1`'s `Ping Reply` in the ethernet network. So, `Router1` must have sent the `Ping Reply` in the Thread traffic. 

In some other random fail of this TC, there is no `PBBR1`'s `Ping Request` to `Router1` in Thread traffic.

A possible cause is that UDP communication within the `GitHub Action Runner VM` is indeed unreliable. 

I think we will change the test to verify that the ping reply is indeed received on the ethernet to eliminate false fails.
