### ISSUE TITLE
Router info (from child's perspective)

### ISSUE THREAD

**Issue by farhangj** [openthread/openthread#6863]
Hi,

I'm wondering what the meaning of otRouterInfo.mAge parameter is., which is also accessible via CLI command "ot parent" from a child device:

e.g.:

uart:~$ ot parent
Ext Addr: 36a5dc9efda1abb0
Rloc: 7c00
Link Quality In: 3
Link Quality Out: 3
**Age: 80**

The age parameter keeps rolling up to 255 (every second increments it by 1 in my case) and then reset to 0 and increments.

In my network I have 4x SEDs their poll period is set to 250ms and 1x FTD router. Age of children (from router perspective) is always 0. but as seen above the age of the router from children's perspective keeps incrementing to 255 seconds and then 0 and up again.

in the [API documentation ](https://openthread.io/reference/struct/ot-router-info) it says "Time last heard". But on top of the 250ms child to router "polls" and ACKs, router is also sending a CoAP message to all children every 20 seconds, with reply back from children. So I don't understand why "mAge" exceeds these intervals (e.g. 250ms or worst case 20 seconds).

I am using nRF NCS v1.6 and OT v1.1.1 on nRF52840dk boards.

**Comment by jwhui** [comment]
The age value is not really meaningful on a Sleepy End Device (SED). The age / last heard value is primarily used to support the MLE protocol. As a result, the last heard value is only updated on a subset of (mostly MLE) messages.

Other devices that are rx-on-when-idle (router and child) will update the last heard value because they participate more actively in the MLE protocol.

Hope that helps.
