### ISSUE TITLE
[github-actions] test_netdata_publisher.py fails intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#6922]
[logs_91695.zip](https://github.com/openthread/openthread/files/6980058/logs_91695.zip)
[packet-verification-1.1-on-1.2-pcaps.zip](https://github.com/openthread/openthread/files/6980059/packet-verification-1.1-on-1.2-pcaps.zip)

```
======================================================================
FAIL: test (__main__.NetDataPublisher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/scripts/thread-cert/test_netdata_publisher.py", line 425, in test
    self.assertTrue(rlocs.count(end_dev1.get_addr16()) == 1)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by abtink** [comment]
Reading the test-case, I have an idea what may be happening here. In the test
- We add an on-mesh prefix entry on an end-device to be published.
- Then we add same on-mesh prefix on all routes (all adds are done together). 
- Due to randomness of how/when publisher decides to add entries in network data, it can happen (though not often) that we add too many (above the desired threshold).
- This then triggers the remove process of the extra entry
-  In this case we would remove the entry form end-device first (due to it being considered lower preference over the same entry from a router). This is actually what we verify in the next step of the test (adding same prefix now with "high" on leader and expect that the entry from `end-dev1` to be removed). 

I think we can make this case robust by adding extra wait time in between the adds on routers (don't add them all together). Will add a PR on this soon.
