### ISSUE TITLE
OpenThread periodically extra sends ParentRequest

### ISSUE THREAD

**Issue by canisLupus1313** [openthread/openthread#7062]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id 27dc37ea8da4d0808134c0046c90db8273d7d03a
2. IEEE 802.15.4 hardware platform Interoperrability
3. Build steps N/A
4. Network topology:
    - Two BBRs
    - Router
    - FED
    - PC

Test steps:
1. Successful Thread network setup
1. Border Router 1 shuts down
1. Thread Router detects that it’s disconnected
1. Thread Router tries to attach to new BR (in this case BR2)
1. The attachment of the Router is successful and Router gets the same Router ID (frames 414-421) but different Partition ID.
1. The FED sends the Parent Request.
1. Thread Router receives it and replies to FED.
1. FED doesn’t send the Child ID Request. Thread Router considers the FED as it’s child.
1. connectivity is OK

Does anyone know why FED sends this Parent Request? It seems that it's not in specification (at least I can't find it).
And This behavior causes some interoperability issues between Thread implementation vendors.

**Comment by abtink** [comment]
@canisLupus1313 , do you enable "[periodic parent search](https://openthread.io/guides/build/features/periodic-parent-search?hl=en)" feature on the FED? If so, the the child would periodically search to see if it can find a better parent (which will start by sending "Parent Request" which still being attached). 

This feature is very useful and came out of the need in actual deployments. Without this, a child will stick to a potentially undesirable parent (e.g. marginal link quality, low RSSI), even if  new Thread devices/routers are installed and there are better parent options for the child to attach to. Note that even a child reset/reboot won't necessarily cause the child to switch its parent (since the child will persist the the parent info in its non-volatile setting and after reset the child would try to first do quick re-attach recovery with its previous parent). 

I believe this feature is allowed by spec. A parent receiving a "Parent Request" from an existing child should not change the child state (in its child table).

**Comment by canisLupus1313** [comment]
@abtink cold You Point me to a speck clause for this behavior?

**Comment by canisLupus1313** [comment]
> I just want to emphasis this, the "periodic parent search" is incredibly useful feature. I would highly discourage disabling it.

I'm not planning on removing nor disabling it.

I can also see that this is disabled by default [here](https://github.com/openthread/openthread/blob/main/src/core/config/parent_search.h#L56) and that default timer is I suppose 9 minutes [here](https://github.com/openthread/openthread/blob/main/src/core/config/parent_search.h#L68). But never the less important thing. 

The thing that interests me the most is that the current Parent cannot remove it's child from it's child table based on just receiving the Parent Request from it. Do You think it would be good to add this statement to speck?

**Comment by canisLupus1313** [comment]
@abtink @jwhui thanks for help/clarification. I already raised Jira in Thread group.
