### ISSUE TITLE
leader respons with ack after calling thread stop

### ISSUE THREAD

**Issue by lmaciejonczyk** [openthread/openthread#7312]
**Topology:**
leader ---- SED/SSED

Git OpenThread commit: 3c260bd7c7444b9bf446429de3fe46fab09162b3 (Wed Jan 12 15:25:21 2022)

**Reproduction steps:**
1. Form the topology
2. On leader side, call: ```thread stop```
3. Observe that leader still respons with ack on child _Data Request_
4. On leader side, call: ```thread start```
5. Try ping devices
6. Observe that the leader-child communication is lost

pcap file with the current behaviour: [pcap_thread_stop_and_still_ack.zip](https://github.com/openthread/openthread/files/7861970/pcap_thread_stop_and_still_ack.zip)

**Expected behavior**
After call "thread stop" the leader should not response with ack so that child reattach the network.

**Comment by jwhui** [comment]
@lmaciejonczyk , I believe this is currently expected behavior. `thread stop` only stops Thread-related protocols, such as MLE and TMF. `ifconfig down` will actually disable the radio.

The Thread 1.1.1 specification does state the following:
```
Rx-off-when-idle Children
SHOULD also periodically (at time intervals indicated by the application) resynchronize by
sending a Child Update Request to their Parent to avoid cases when the MAC Data Request
is being acknowledged erroneously by a receiver that is not a valid Parent.
```

You can also take a look at OpenThread's [Periodic Parent Search](https://openthread.io/guides/build/features/child-supervision) feature that also addresses this issue.

**Comment by lmaciejonczyk** [comment]
I've been missing it. It makes sense to me now, thanks.
