### ISSUE TITLE
[mle] parent does not assign Child ID if network data is "stale"

### ISSUE THREAD

**Issue by dismirlian** [openthread/openthread#7499]
I don't know if this is a bug, or the intended behavior.

In a network with many SEDs and two or three REEDs, if we try to activate the built-in commissioners of the REEDs periodically, the parents may constantly deny assigning Child IDs. The error we see in the logs is `Failed to process Child ID Request: InvalidState`. We think that the invalid state error comes from [Mle::AppendNetworkData](https://github.com/openthread/openthread/blob/dd4ce786a8fa67c66265408a923535f4b5e980f6/src/core/thread/mle.cpp#L1200) called from [MleRouter::SendChildIdResponse](https://github.com/openthread/openthread/blob/e04c8e330773cf3fcc1acd00b18e7ea355e134ad/src/core/thread/mle_router.cpp#L3108) which is in turn called from [MleRouter::HandleChildIdRequest](https://github.com/openthread/openthread/blob/e04c8e330773cf3fcc1acd00b18e7ea355e134ad/src/core/thread/mle_router.cpp#L2397). It seems that `Mle::AppendNetworkData` returns `kErrorInvalidState` if the parent's network data is stale (`mRetrieveNewNetworkData == true`). I don't think this is necessarily a bad thing, but if network data changes constantly (which *is* definitely a bad thing), then the children never attach.

A possible "optimization" would be to allow children with stale data (ignore `mRetrieveNetworkData` when handling this request), but I don't know if there could be unintended side effects. If I understand correctly, the network data will propagate to the child when it is updated.

What do you think?

Thanks!

**Comment by jwhui** [comment]
@dismirlian , thanks for raising this issue!

The logic in question was added in #3354. The scenario it was trying to address was a Leader that recently restarted and is trying to restore its state from neighboring devices. In this case, we do not want the Leader to be sending Network Data until it has synchronized with the network. There are other similar situations, like when a devices changes partitions. We could consider allowing a child to attach when the Network Data is stale, but I think we need to be careful to differentiate between "stale" and "invalid".

What I'd like to first understand is why `mRetrieveNewNetworkData` is `true` more often than not, even when you are periodically activating a commissioner. When a router receives an update to the Network Data, it sends an unsolicited Data Response message to provide neighboring nodes with the updated Network Data. If a device learns of an update from an Advertisement, then it will send a Data Request and should immediately receive a Data Response.

Is it possible for you to grab some detailed device logs when this issue is occurring so that we can better diagnose the issue?

**Comment by dismirlian** [comment]
Hi @jwhui, thanks for your answer!

Now I understand the reason for this logic. I think that allowing a child to attach when the Network Data is stale is only an "optimization".

We are also trying to understand why `mRetrieveNewNetworkData` is usually `true`. We think this is related to another issue (#7513), partitions frequently merging/unmerging, and commissioners "fighting" (#6951). We will try to solve all these before this one.

We will return with more details, if we can catch some relevant logs. Any idea of what to look at?

**Comment by jwhui** [comment]
Closing stale issue.
