### ISSUE TITLE
OTBR cannot parse large SRP update due to fragmentation

### ISSUE THREAD

**Issue by Damian-Nordic** [openthread/openthread#7742]
**Describe the bug**
SRP server on the OTBR fails to parse an SRP update that is too large to fit in a single IPv6 packet. In such a case the datagram is fragmented and the SRP server tries to process the first fragment alone which results in the following error:
```
May 23 11:49:09 b22caefa12ee otbr-agent[210]: 01:54:23.728 [W] SrpServer-----: Failed to process Service Discovery instructions: Parse
May 23 11:49:09 b22caefa12ee otbr-agent[210]: 01:54:23.728 [W] SrpServer-----: Failed to process DNS Update section: Parse
```
I checked that the failing line of code is:
```c
SuccessOrExit(error = aMessage.Read(signatureOffset, signature));
```
Root cause: `signatureOffset` is greater than the payload length.

I'm filing an issue here instead of in the OTBR repo as I'm not sure if an SRP client should create such big updates at all or maybe they should be split into smaller ones.

**To Reproduce**

1. Run OTBR (OTBR SHA: bb3c1e) and form a network.
2. Build OpenThread CLI for nRF 52840 DK (OpenThread SHA: 130afd9) with `OPENTHREAD_CONFIG_SRP_CLIENT_BUFFERS_MAX_SERVICES` changed to 6.
3. Run the following commands on the CLI:
```
ifconfig up
dataset set active <otbr-dataset>
thread start
srp client autostart enable
srp client service add 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743174787431747874317478743174787431747874317478743174787431747874317478743174787431747874317478
srp client service add 1123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743274787432747874327478743274787432747874327478743274787432747874327478743274787432747874327478
srp client service add 2123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743374787433747874337478743374787433747874337478743374787433747874337478743374787433747874337478
srp client service add 3123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde _matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6 12345 0 0 364b45593d7478743474787434747874347478743474787434747874347478743474787434747874347478743474787434747874347478
srp client host name hosthosthosthosthosthosthosthosthosthosthosthosthosthosthosthos
srp client host address fd11:22:0:0:a295:b6e6:a120:c3c
```
4. Observe that the services are never registered:
```
$ srp client service
instance:"3123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
instance:"2123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
instance:"1123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
instance:"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcde", name:"_matterc._udp,_A1,_A2,_A3,_A4,_A5,_A6", state:Adding, port:12345, priority:0, weight:0
```

**Expected behavior**
Successful registration of the services.

**Console/log output**
Already provided above.

**Additional context**
Building OTBR with `OT_IP6_FRAGM` enabled solves the issue, because then the fragmented datagram is reassembled on the OTBR side.

**Comment by abtink** [comment]
Thanks @Damian-Nordic .

I assume `OT_IP6_FRAGM` was enabled client side but not OTBR side, and so enabling it on OTBR side allows larger IPv6 messages to be delivered.

I guess this happens if the SRP update message becomes larger than MTU support by underlying IP stack (1280 for Thread).
We can rely on IP fragmentation to handle such situations. 

> ... as I'm not sure if an SRP client should create such big updates at all or maybe they should be split into smaller ones.

On SRP client behavior: I don't think we have any specific behavior specified for this (e.g. in SRP draft)
An idea can be that "if there are multiple services, have client register them in separate messages (if they don't fit in same MTU limited message)".
- But I am not sure if this can help address all cases:
   - For example, we can have a single service with many sub-types and large TXT record and host with many addresses that then create an SRP update message over MTU size 
   (SRP does require all of the records belonging to the same service to be included in the same message).
   - If I am not mistaken TXT record itself can be up to 64K (though there are recommendations that it should be kept small, I recall a suggestion of it being kept below 1400 bytes)
- Looking at the code and implementation in OT adding such behavior (registering services in separate msgs if there are multiple services that won't fit in one MTU) may not be an easy/small change (it requires new mechanism/states to track which services are registered in which message). I guess technically doable but for sure adds complexity and increase code size.

Here are my thoughts on this:
- First question is if such use-case of many large service registrations practical/useful or more of a corner/extreme case?
- Can we rely on IP fragmentation for this case (if neede).
- In my view, this may be more of a corner case so I lean towards having it handled by IP fragmentation (if needed) or maybe managed by the next layer (e.g., have next layer register services separately).

**Comment by Damian-Nordic** [comment]
@abtink Thanks for you comment.

Well, the issue was found when performing Matter test cases, so it's not a corner case, I'm afraid :). Unfortunately, Matter with its multi-fabric support allows a device to register many services, so even if a device supports the minimum number of fabrics required by the Matter specification it is possible to exhaust the MTU. Also, some TXT entries can be pretty long (128 or 256 bytes IIRC), so it could take just a few services to fill an IP packet.

I agree it would simplify a lot of things if we could handle that by IP fragmentation/reassembly, but wouldn't it mean that OT spec needs to require OT_IP6_FRAGM enabled on all devices acting as an SRP server? I'm not familiar with existing requirements regarding IP fragmentation. Do you see any potential issues with such a requirement.

**Comment by abtink** [comment]
I don't see any immediate issue with requiring IP frag to be supported on BRs (and/or clients).

It sounds like a reasonable solution to me (in sense that it addresses multiple situations, many service of single service with large TXTrecord  or single service with many sub-types and/or host addresses, etc).

Thoughts? @jwhui , @Abhayakara.

**Comment by Abhayakara** [comment]
I think the right solution in this case is to require TCP. The design of SRP for Thread was never intended to be able to manage UDP datagrams large enough to fragment. Even UDP datagrams the size of the MTU are too big.

**Comment by Abhayakara** [comment]
FWIW, the SRP specification actually encourages using DNS-over-TLS for SRP updates, and makes an _exception_ for constrained networks. If Matter is sending huge updates, this exception doesn't apply.

**Comment by Abhayakara** [comment]
That said, instance names that large are a really, really dumb idea.

**Comment by Damian-Nordic** [comment]
@Abhayakara Matter doesn't use that large instance names. In the description I wanted to provide fewer steps that still reproduce the issue. Also, Matter devices can still be classified as constrained in terms of available memory etc., so although some SRP updates can be big, it doesn't imply that resource usage is not a concern.

**Comment by jwhui** [comment]
> @Abhayakara Matter doesn't use that large instance names. In the description I wanted to provide fewer steps that still reproduce the issue. Also, Matter devices can still be classified as constrained in terms of available memory etc., so although some SRP updates can be big, it doesn't imply that resource usage is not a concern.

@Damian-Nordic , can you help provide the actual Matter example that generates an SRP Update larger than the IPv6 MTU? I understand that this is due to a Matter test case and I'm wondering if the test case itself is actually testing something meaningful.

**Comment by simonlingoogle** [comment]
I think TCP is the right way to go for large DNS messages.

**Comment by abtink** [comment]
Submitted: 
- https://github.com/openthread/openthread/pull/7776

Some thoughts:
- While the matter use-case where a device may be part of multiple fabrics and therefore need to register many services (and sub-types) is a possible scenario, my understanding/expectation is that it is not a common use-case. 
- I agree using TCP to handle larger DNS update message is the right design choice, but requiring it on computationally less-capable devices (to support this use-case) somewhat defeats the intention behind SRP using UDP on constrained networks.
- The PR above will help allow this use-case to be supported by having SRP client perform MTU check when it prepares the SRP update message and if it is larger than MTU, temporarily switches to "single service mode" which enforces the SRP update message to include a single service (practically registering services one-by-one while they cannot fit in a single MTU).
- One main goal for me adding this PR was to keep the change small (so we can support the use-case while not adding a lot of code-size overhead and/or complexity).

**Comment by Abhayakara** [comment]
One additional thing to say about this is that it appears that perhaps the OpenThread client is always sending everything, which is unnecessary. One way to keep things small is to have each service have its own renewal cycle. Only send service updates when the time comes to register or renew the service.

It also looks a bit like the OpenThread client may be sending more stuff than it needs to, or should. E.g. it looks like when removing a service with subtypes, the removal includes the subtypes. This isn't necessary, because the subtypes depend on the service. It's always the case that when a service is removed, the subtypes are removed.

The disadvantage of not sending everything at once is that you always have to send the host update, I think. Maybe that shouldn't be required in the case that you're just adding or renewing a service, if the host is on a different renewal schedule. And of course if you send everything at once, that's less duplication of effort in constructing and sending the packets. But you could for example have a threshold, where if the aggregate packet exceeds a certain size after a new service is added, then you start doing disconnected renewal cycles.

**Comment by abtink** [comment]
> One additional thing to say about this is that it appears that perhaps the OpenThread client is always sending everything, which is unnecessary. 

This is not really the case. Each service state is tracked  . Services that are already registered are not included in a prepared SRP update.  Only newly added/removed services are included in an SRP update along with any that need a refresh (their lease expired).

If the user adds multiple services at the same time, we try to send them together (to avoid sending multiple updates back-to-back). This is realized by adding a short wait delay once something get changed and we need to send an update message.

We also have a mechanism "opportunistic early refresh": If we are already going to send an SRP update we check if there are any existing registered services that their lease time is about to expire and can decide to refresh them early. This mechanism itself is configurable, it can be fully disabled or enabled and we can configure how we determine if a service lease time is about expire (defined as a configurable fraction of the granted lease time, e.g., if 1/10 of lease time remaining). The goal of this is to help align service refreshes if possible (help reduce traffic on sleepy or constrained devices).

> It also looks a bit like the OpenThread client may be sending more stuff than it needs to, or should. E.g. it looks like when removing a service with subtypes, the removal includes the subtypes. This isn't necessary, because the subtypes depend on the service. It's always the case that when a service is removed, the subtypes are removed.

Checking the code I think you are correct. We can optimize this later (will do in a future PR).

**Comment by Damian-Nordic** [comment]
@abtink Thanks for the change! The reason why all services are updated in the case of Matter is that Matter's common DNS-SD component is stateless and always refreshes all services not to occupy memory both in the platform-agnostic and platform-specific DNS-SD layers. I'll think if it's possible to avoid that at low cost, but having a safety mechanism in OpenThread will definitely help, too.

**Comment by gabekassel** [comment]
@jwhui @abtink reading the comments here, it sounds like you still suggest leaving IP6_FRAGM off on the OTBR and pushed this to the client?

**Comment by abtink** [comment]
@gabekassel , yes. exactly. New behavior on client added in this
- https://github.com/openthread/openthread/pull/7776.
