### ISSUE TITLE
[tcplp] code scanning alert - multiplication result converted to larger type

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#8378]
Tracking issue for:
- [ ] https://github.com/openthread/openthread/security/code-scanning/1
- [ ] https://github.com/openthread/openthread/security/code-scanning/2

@samkumar, thoughts on these alerts?

**Comment by samkumar** [comment]
@jwhui I'm trying to follow those links but they aren't working for me (I get GitHub's 404 page). Perhaps I need to be granted access?

**Comment by jwhui** [comment]
> @jwhui I'm trying to follow those links but they aren't working for me (I get GitHub's 404 page). Perhaps I need to be granted access?

@samkumar , I adjusted the permissions. Can you try again? Thanks.

**Comment by samkumar** [comment]
This is interesting --- this code is taken directly from FreeBSD. I think there are two options here.
1. I can add in casts to make the errors go away.
2. I can leave the code as is since it's taken from FreeBSD (and presumably suppress the warnings).
There seems to be no downside to adding the casts, so I lean toward Option 1. Does that sound OK to you @jwhui ?

**Comment by jwhui** [comment]
@samkumar , your proposed solution (option 1) sounds good to me. Thanks.

**Comment by samkumar** [comment]
I opened Pull Request #8578, which I believe will fix these code scanning alerts.
