### ISSUE TITLE
The Link Metrics Status Sub-TLV in Link Metrics Management Response message is 254(Failure - Other failure)

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/openthread#8604]
The Test 7 1 1 Single Shot With Enhanced Acks failed during the Thread Certification test. Is there a build config for this feature. Or are we using too low a version of the stack?

Border Router:
Git commit id ot-br-posix GSDK v4.1.3
IEEE 802.15.4 hardware platform : EFR32MG21F768 base on GSDK v4.1.3

![image](https://user-images.githubusercontent.com/97089879/210308081-0864cb66-f438-4bef-a79e-6aabb97a3a66.png)

![image](https://user-images.githubusercontent.com/97089879/210308768-1c47cf13-8d93-4d63-9376-efc7d2e0bc71.png)

Network Key: 33221100445566778899aabbccddeeff
[Fail_L_7_1_1_Leader_v57.0_2022_12_26-17_47_06_Ch-11.zip](https://github.com/openthread/openthread/files/10334604/Fail_L_7_1_1_Leader_v57.0_2022_12_26-17_47_06_Ch-11.zip)
[Fail_L_7_1_1_Leader_v57.0_2022_12_26-17_50_36.pdf](https://github.com/openthread/openthread/files/10334605/Fail_L_7_1_1_Leader_v57.0_2022_12_26-17_50_36.pdf)

**Comment by jinpeng1989** [comment]
Any updates on this issue?

**Comment by Irving-cl** [comment]
Hi @jinpeng1989,

Could you check if you have enabled the option `OPENTHREAD_CONFIG_MLE_LINK_METRICS_SUBJECT_ENABLE` when building RCP? And please also make sure if `otPlatRadioConfigureEnhAckProbing` have been implemented on EFR platform. For example:
* On simulation platform: https://github.com/openthread/openthread/blob/main/examples/platforms/simulation/radio.c#L1345
* On Nordic platform: https://github.com/openthread/ot-nrf528xx/blob/main/src/src/radio.c#L1412

Let's first check if these things are good. Then we can try to add some logs in [LinkMetrics::ConfigureEnhAckProbing](https://github.com/openthread/openthread/blob/main/src/core/thread/link_metrics.cpp#L616) and see which steps did it return the error.

BTW, I think we'd better discuss certification related issue on JIRA, instead of github issues. So please create JIRAs for certification related issues. I would love to help.

**Comment by jwhui** [comment]
Closing stale issue.
